=== luisgasa-uax/lm-asir-on-2526/sesion2/jueves/gimnasio.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="gimnasio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sala" maxOccurs="unbounded"> 
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="uso" type="xs:string"></xs:element>
                            <xs:element name="capacidad" type="xs:int"></xs:element>
                            <xs:element name="hora-apertura" type="xs:int"></xs:element>
                            <xs:element name="hora-cierre" type="xs:int"></xs:element>
                            <xs:element name="monitor" type="xs:string" minOccurs="0" maxOccurs="2"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="numero-sala" type="xs:int"></xs:attribute>
                        <xs:attribute name="musica" type="xs:string" use="required"></xs:attribute>

                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== luisgasa-uax/lm-asir-on-2526/sesion2/jueves/gimnasio.xml
<gimnasio 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="gimnasio.xsd"
>
    <sala numero-sala="1" musica="reggaeton">
        <uso>Spinning</uso>
        <capacidad>30</capacidad>
        <hora-apertura>10</hora-apertura>
        <hora-cierre>21</hora-cierre>
        <monitor>Alisson</monitor>
    </sala>

    <sala numero-sala="2" musica="metal">
        <uso>Crossfit</uso>
        <capacidad>15</capacidad>
        <hora-apertura>6</hora-apertura>
        <hora-cierre>24</hora-cierre>
    </sala>

    <sala numero-sala="3" musica="salsa">
        <uso>Zumba</uso>
        <capacidad>25</capacidad>
        <hora-apertura>16</hora-apertura>
        <hora-cierre>22</hora-cierre>
        <monitor>Ligia</monitor>
        <monitor>Ramón</monitor>
    </sala>
</gimnasio>

<!-- 
Ampliamos: 
    Vamos a añadir algunas cosillas y restricciones a mayores:
    - cantidad máxima de elementos de un tipo
    - cantidad mínima de elementos de un tipo
    - añadir un atributo nuevo
    - obligatoriedad de incorporar un atributo en un elemento. Por ejemplo el música de sala
    - elemento con atributo y contenido simple
-->
