=== luisgasa-uax/lm-asir-on-2526/sesion2/jueves/usuarios.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="usuarios"></xs:element>

    <xs:element name="usuario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"></xs:element>
                <xs:element name="edad" type="xs:int"></xs:element>
                <xs:element name="email" type="xs:string"></xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:int"></xs:attribute>
            <!-- los atributos van fuera y después del sequence-->
        </xs:complexType>
    </xs:element>
</xs:schema>

=== luisgasa-uax/lm-asir-on-2526/sesion2/jueves/usuarios.xml
<usuarios 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="usuarios.xsd"
>
    <usuario id="2">
        <nombre>Javier</nombre>
        <edad>30</edad>
        <email>javier@myuax.es</email>
    </usuario>

    <pepe>
        <usuario id="1">
            <nombre>Aída</nombre>
            <edad>26</edad>
            <email>aida@myuax.es</email>
        </usuario>
    </pepe>
</usuarios>
