=== luisgasa-uax/lm-asir-on-2526/sesion2/02_usuarios.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- 
xs:schema es la etiqueta contenedora del XSD
xmlns xml Name Space

utilizaremos xs: como prefijo de las etiquetas del esquema
-->

<xs:element name="usuarios">
    <xs:complexType>    <!-- por que contiene otros elementos -->
        <xs:sequence>
            
            <xs:element name="usuario" maxOccurs="unbounded"> <!-- maxOccurs="unbounded" indica que podemos tener una cantidad indefinida de elementos hijo tipo usuario -->
                <xs:complexType>
                    <xs:sequence> 
                        <xs:element name="nombre" type="xs:string"></xs:element>
                        <xs:element name="edad" type="xs:int"></xs:element>
                        <xs:element name="estatura" type="xs:decimal" minOccurs="0"></xs:element>
                        <xs:element name="email" type="xs:string" minOccurs="1"
                        maxOccurs="unbounded"></xs:element>
                    </xs:sequence>

                    <!-- los atributos se definen dentro del complexType, pero fuera de la secuencia -->
                    <xs:attribute name="id" type="xs:int" use="required"></xs:attribute>

                </xs:complexType>
            </xs:element>
            
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== luisgasa-uax/lm-asir-on-2526/sesion2/01_usuarios_base.xml
<usuarios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
          xsi:noNamespaceSchemaLocation="02_usuarios.xsd"
>
    <usuario id="1">
        <nombre>Ana</nombre>
        <edad>25</edad>
        <estatura>1.67</estatura>
        <email>ana@myuax.es</email>
        <email>ana@gmail.es</email>
        <email>ana@hotmail.es</email>

    </usuario>
    
    <usuario id="2">
        <nombre>Luis</nombre>
        <edad>30</edad>
        <estatura>1.87</estatura>
        <email>luis@myuax.es</email>

    </usuario>
</usuarios>
