=== luisgasa-uax/lm-asir-on-2526/sesion2/servidores.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- este XSD sí valida todo el documento de servidores.xml 
-->
  <xs:element name="servidores">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="servidor" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"></xs:element>
              <xs:element name="ip" type="xs:string"></xs:element>


              <xs:element name="ssoo">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="tipo" type="xs:string" use="optional"></xs:attribute>
                      <xs:attribute name="version" type="xs:string" use="required"></xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>

              <!-- <xs:element name="usuario" type="xs:string"/> -->
              <xs:element name="usuario">
                <xs:complexType>
                  <xs:choice>
                    <xs:element name="root" />
                    <xs:element name="admin" />
                  </xs:choice>
                </xs:complexType>
              </xs:element>


              <xs:element name="password" type="xs:string" minOccurs="0" />

              <!-- RESTRICCIONES DE POSIBLES VALORES -->
              <!-- puertos válidos 1 al 65535 -->
              <xs:element name="puerto">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:minInclusive value="1" />
                    <xs:maxInclusive value="65535" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>

              <xs:element name="fechaInstalacion" type="xs:date" minOccurs="1" maxOccurs="1"></xs:element>

              <xs:element name="urlServidor" type="xs:anyURI" minOccurs="1"></xs:element>

              <xs:element name="usuarios" minOccurs="0">
                <xs:complexType>
                  <xs:sequence> <!-- para obligar a que mantenga un orden específico -->
                    <xs:element name="usuario" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:all> <!-- para no obligar a que mantenga un orden específico -->
                          <xs:element name="nombre" type="xs:string"></xs:element>
                          
                          
                          <!-- RESTRICCIONES DE TEXTO: con ENUMERATION-->
                          <xs:element name="rol">
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="Developer" />
                                <xs:enumeration value="SysAdmin" />
                                <xs:enumeration value="Security" />
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>

                          <xs:element name="activo" type="xs:boolean"></xs:element>

                          <!-- ejemplo de uso de CHOICE -->
                          <xs:element name="autenticacion">
                            <xs:complexType>
                              <xs:choice>
                                <xs:element name="token" type="xs:string"></xs:element>
                                <xs:element name="password" type="xs:string"></xs:element>
                              </xs:choice>
                            </xs:complexType>
                          </xs:element>

                        </xs:all>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

            </xs:sequence>

            <xs:attribute name="id" type="xs:ID" />

          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== luisgasa-uax/lm-asir-on-2526/sesion2/04_servidores.xml
<!-- crea un documento XSD que valide este XML -->

<servidores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xsi:noNamespaceSchemaLocation="servidores.xsd"
>
  <servidor id="srv-1">
    <nombre>srv-web</nombre>
    <ip>192.168.1.10</ip>
    <ssoo tipo="linux" version="24.04.4 LTS">Ubuntu Server</ssoo>
    <!-- <usuario>admin</usuario> -->
    <usuario>
      <root/>
    </usuario>
    <puerto>57</puerto>
    <fechaInstalacion>2026-03-04</fechaInstalacion> <!-- YYYY-MM-DD -->
    <urlServidor>192.168.0.8</urlServidor>
  </servidor>

  <servidor id="srv-2">
    <nombre>srv-db</nombre>
    <ip>192.168.1.20</ip>
    <ssoo version="Server 2025">Windows Server</ssoo>
    <!-- <usuario>root</usuario> --> <!-- O root o Admin --> 
    <usuario>
      <admin/>
    </usuario>
    <password>1234</password>
    <puerto>65</puerto>
    <fechaInstalacion>2026-03-24</fechaInstalacion>
    <urlServidor>192.168.0.5</urlServidor>
  </servidor>

  <servidor id="asdlkfjasdfasd">
    <nombre>svr-remoteDesktop</nombre>
    <ip>192.168.1.7</ip>
    <ssoo version="Server 2025">Windows Server</ssoo>
    <!-- <usuario>root</usuario> -->
    <usuario>
      <admin/>
      <!-- <admin></admin>  esta opción es igual de válida -->
    </usuario>
    <password>1234</password>
    <puerto>3200</puerto>
    <fechaInstalacion>2026-02-24</fechaInstalacion>
    <urlServidor>http://escritorio-remoto.local</urlServidor>
    
    <usuarios>
      <usuario>
        <nombre>Marta</nombre>
        <rol>SysAdmin</rol>
        <activo>true</activo>
        <autenticacion>
          <token>234567890</token> 
          <!-- <password>aisoduakñlsdjf ña</password> -->
        </autenticacion>
      </usuario>

      <usuario>
        <activo>false</activo>
        <rol>Developer</rol>
        <nombre>Antonio</nombre>
        <autenticacion>
          <password>ñalsdjlfkas-dfñaos</password> 
        </autenticacion>
      </usuario>

      <usuario>
        <activo>false</activo>
        <rol>Security</rol>
        <nombre>Alberto</nombre>
        <autenticacion>
          <password>ñalsdjlfkas-dfñaos</password> 
        </autenticacion>
      </usuario>
    </usuarios>
  </servidor>

</servidores>
